[capability::goatsearch_user]

[capability::goatsearch_admin]

[role_admin]
goatsearch_admin = enabled
goatsearch_user = enabled

[role_goatsearch_admin]
goatsearch_admin = enabled
goatsearch_user = enabled

[role_goatsearch_user]
goatsearch_user = enabled

[role_sc_admin]
goatsearch_admin = enabled
goatsearch_user = enabled
